services:
- docker
before_install:
- "./.travis/main.sh"
script:
- make build
- make test
deploy:
  provider: script
  script: bash ./.travis/docker_push.sh
  skip_cleanup: true
  on:
    tags: true
    branch: master
